graph:
  db:
    username: neo4j
    uri:
    password:

mongo-hr:
  offline-sim-db-url: "mongodb://localhost:27017"
  offline-sim-db-name: "graph_hr"

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update

ui-uri: http://ec2-3-133-161-239.us-east-2.compute.amazonaws.com:3000